Repository alma/alma-php-client, pull requests merged in 2024-07, with the labels that each got.

#118 [DEVX] Fix branch for release-drafter + don't publish internal changes in changelog
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/backport-pull-request.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-pull-request.yml
Labels: type: devx

#121 [DEVX] Update Slack release message
  .github/workflows/release-publish.yml
Labels: type: devx

#123 [DEVX] Exclude release PRs from the changelog
  .github/release-drafter.yml
Labels: type: devx

#125 Feature/ecom 1867 php client rework integration test in php client
  .DS_Store
  .github/release-drafter.yml
  .github/renovate.json
  .github/workflows/aqua.yml
  .gitignore
  Taskfile.php.yml
  phpunit.dist.xml
  tests/Integration/Endpoints/PaymentsTest.php
  tests/Integration/Legacy/Endpoints/PaymentsTest.php
  tests/Integration/PHP7_0/Endpoints/PaymentsTest.php
  tests/Integration/PHP8_1/Endpoints/PaymentsTest.php
  tests/legacy_integration_tests.sh
Labels: type: feature

#124 feature: refactor order and add updateTracking put endpoint
  src/Endpoints/Orders.php
  src/Entities/Order.php
  tests/Integration/Endpoints/OrdersTest.php
  tests/Integration/Endpoints/PaymentsTest.php
  tests/Integration/TestHelpers/ClientTestHelper.php
  tests/Integration/TestHelpers/PaymentTestHelper.php
  tests/Unit/Endpoints/OrdersTest.php
  tests/Unit/Endpoints/PaymentsTest.php
  tests/Unit/Entities/OrderTest.php
Labels: minor, type: feature

#126 [DEVX] Fix release PR not triggering workflows
  .github/workflows/release-pull-request.yml
Labels: type: devx

#127 Change shipment data endpoint
  phpunit.ci.xml
  src/Endpoints/Insurance.php
  src/Endpoints/Orders.php
  src/Entities/Order.php
  tests/Integration/Endpoints/OrdersTest.php
  tests/Unit/Endpoints/OrdersTest.php
  tests/Unit/Entities/OrderTest.php
Labels: minor, type: feature

#130 Fix typo in release-publish workflow
  .github/workflows/release-publish.yml
Labels: type: devx
