Repository alma/alma-php-client, pull requests merged in 2025-09, with the labels that each got.

#182 feat: Add ShareOfCheckoutDto
  src/DTO/ShareOfCheckout/ShareOfCheckoutDto.php
  src/DTO/ShareOfCheckout/ShareOfCheckoutOrderDto.php
  src/DTO/ShareOfCheckout/ShareOfCheckoutPaymentMethodDto.php
  src/DTO/ShareOfCheckout/ShareOfCheckoutTotalOrderDto.php
  tests/Unit/DTO/ShareOfCheckout/ShareOfCheckoutDtoTest.php
  tests/Unit/DTO/ShareOfCheckout/ShareOfCheckoutOrderDtoTest.php
  tests/Unit/DTO/ShareOfCheckout/ShareOfCheckoutPaymentMethodDtoTest.php
  tests/Unit/DTO/ShareOfCheckout/ShareOfCheckoutTotalOrderDtoTest.php
Labels: type: feature

#187 ci: run on prs/pushes to the feature/3.0 branch
  .github/workflows/ci.yml
Labels: type: ci

#188 feat: refactor merchant business event DTO
  src/DTO/MerchantBusinessEvent/AbstractBusinessEventDto.php
  src/DTO/MerchantBusinessEvent/CartInitiatedBusinessEventDto.php
  src/DTO/MerchantBusinessEvent/OrderConfirmedBusinessEventDto.php
  src/Endpoint/MerchantEndpoint.php
  tests/Unit/DTO/MerchantBusinessEvent/CartInitiatedBusinessEventDtoTest.php
  tests/Unit/DTO/MerchantBusinessEvent/OrderConfirmedBusinessEventDtoTest.php
  tests/Unit/Endpoint/MerchantEndpointTest.php
Labels: type: feature

#186 Fix/pre commit
  Taskfile.php.yml
  Taskfile.yml
  lint.Dockerfile
  php-compatibility.Dockerfile
Labels: type: bugfix

#203 fix: remove sleep in test for release
  tests/Integration/Endpoints/DataExportsTest.php
Labels: skip-changelog

#205 Fix task dist command
  Taskfile.yml
Labels: type: devx
